//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOfficeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> Age { get; set; }
        public string LastVisit { get; set; }
        public string Gender { get; set; }
        public int NbreVisits { get; set; }
        public Nullable<int> CIN { get; set; }
        public string Adress { get; set; }
        public Nullable<int> IDDoct { get; set; }
    }
}
